# Generated by Django 4.1.5 on 2023-02-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_assets_lifespan_alter_assets_warantee_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='Date_Assigned',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.employee'),
        ),
    ]
