# Generated by Django 4.1.7 on 2023-02-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
